---
- hosts: all
  sudo: true
  vars:
     packages: [ 'git' ]
  tasks:
  - name: Install Package
    apt: name={{ item }} state=latest
    with_items: packages


#---
#- hosts: all
#  tasks:
#     - name: Install httpd Package
#       apt: name=httpd state=latest
